[mysqld]
datadir=D:/digital product/SASS/simpan-pinjam/.tooling/mariadb-data
port=3307
[client]
port=3307
plugin-dir=D:\digital product\SASS\simpan-pinjam\.tooling\mariadb\mariadb-11.4.7-winx64/lib/plugin
